# Generated by Django 6.1.1 on 2026-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year_of_manufacture', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('imported', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
